version: "3.7"
services:
    api:
      build: .
      depends_on:
        - db
      ports: 
        - 8000:8000 
      volumes:
        - $PWD:/usr/src/app:ro
      # env_file:
      #     -./.env   
      environment:
          # - PATH = ./.env
        DATABASE_HOSTNAME: db
        DATABASE_PORT: 5432
        DATABASE_PASSWORD: root
        DATABASE_NAME: fastapi
        DATABASE_USERNAME: postgres
        SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
        ALGORITHM: HS256
        ACCESS_TOKEN_EXPIRED_MINUTES: 30   
      # command: bash -c "alembic upgrade head"

    db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: root
        POSTGRES_DB: fastapi
      volumes: 
        - postgres-db:/var/lib/postgresql/data
  
volumes:
  postgres-db:
















































    # # MySQL container
    # mysql:
    #   # Use mysql:8.0.19 image
    #   image: mariadb
    #   ports:
    #   - '3309:3306'
    #   # Connect to "my-network" network, as defined below
    #   # networks:
    #   #   - my-network
    #   # Pass a list of environment variables to the container
    #   environment:
    #     MARIADB_ROOT_PASSWORD: root
    #     MARIADB_DATABASE: fastapi

    # # phpMyAdmin container
    # phpmyadmin:
    #   # Use phpmyadmin/phpmyadmin:5.0.2 image
    #   image: phpmyadmin
    #   # Connect to "my-network" network, as defined below
    #   # networks:
    #   #   - my-network
    #   # Map port 8080 on the host to port 80 inside the container
    #   # Syntax is: "HOST_PORT:CONTAINER_PORT"
    #   ports:
    #     - "8080:80"
    #   # Pass a list of environment variables to the container
    #   environment:
    #     PMA_HOST: mysql
    #   # Wait for "mysql" container to start first
    #   depends_on:
    #     - mysql

# Define networks
# networks:
#   my-network:









#     db:
#       image: mysql:8.0.19
#       networks:
#         - my-network      

#       environment:
#         - MYSQL_ROOT_PASSWORD = root
#         - MYSQL_DATABASE = fastapi

#     phpmyadmin:
#       image: phpmyadmin/phpmyadmin:5.0.1
#       networks:
#         - my-network      
#       restart: always
#       ports:
#         - 8080:80
#       environment:
#         - PMA_ARBITRARY = 1
#         - PMA_HOST = db
#       depends_on:
#         - db

# networks:
#   my-network:
#       volumes: 
#               - mysql-db:/var/lib/mysql/data

# volumes:
#    mysql-db:
      
